name: Tests
on: push
jobs:
  test:
    runs-on: alpine-plus
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nix
        uses: actions/nix-quick-install-action@v27
      - name: Setup cachix
        uses: actions/cachix-action@master
      - name: Test crate
        run: cargo test
